#/
# @license Apache-2.0
#
# Copyright (c) 2023 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

name: 🚀 Application
description: I'd like to submit my final application for Outreachy!
title: "[Project]: "
labels: ["Outreachy", "May 2025"]
body:
  - type: markdown
    attributes:
      value: |
        * * *
        ## Your Background

        We'd like to get to know you and your background!

  - type: input
    id: full_name
    attributes:
      label: Full name
      description: What is your full name?
      placeholder: e.g., Jane Doe
    validations:
      required: true

  - type: textarea
    id: bio
    attributes:
      label: Short biography
      description: Please provide a brief overview of your background, including any education/professional qualifications (e.g., university degrees, certificates, etc), technical competencies (e.g., C/C++, JavaScript, CI/CD), and general interests (e.g., high-performance numerical computing, machine learning, frontend development).
    validations:
      required: true

  - type: input
    id: timezone
    attributes:
      label: Timezone
      description: In what timezone are you located?
      placeholder: US Pacific Time
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we contact you? This may include an e-mail address, GitHub username, or other handle. If you have multiple handles/usernames, please list all handles and usernames that you want us to know about in order to help us associate your various usernames with you. Separate each entry with a comma.
      placeholder: email:jane@doe.com,github:janedoe123
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        * * *

        ## Programming Experience

        Help us understand your programming experience! Don't worry if you are relatively new to programming. Many contributors start fresh, and we can help teach you what you need to know. :smile:

  - type: textarea
    id: tech_experience
    attributes:
      label: Programming experience
      description: What is your experience programming? Tell us about something that you've created!
    validations:
      required: true

  - type: dropdown
    id: tech_git
    attributes:
      label: Version control
      description: Have you ever used Git for version control?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: tech_project_contributions
    attributes:
      label: Contributions to Project
      description: Please provide a brief summary of your contributions
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        * * *

        ## Project Description

        Tell us about your proposal!

        When detailing the project schedule, you are advised to note where along the way you could formulate a pull request. Ideally, pull requests should be points where you can have self-contained, well-documented, and tested pieces of functionality. Breaking the project into smaller sub-tasks which can be completed as part of one or more pull requests helps to keep branch merges and code reviews reasonable. A large code dump at the end of the program will likely be hard to review and merge before the project deadline.

        Please do **not** copy verbatim text from the list of project ideas or from other people's discussions about your project. Always write your proposal in your own words.

        If you include any significant text or code from another source in your application, you must properly cite the included material. All papers or references that you use or plan to use must be cited. Place all citations in a "References" section at the bottom of each appliable application section. Copying text without citation is plagarism and will result in your application being rejected.

        For an example of a well-written and clearly articulated GSoC proposal, see Aaron Meurer's [2009 SymPy GSoC proposal](https://github.com/sympy/sympy/wiki/GSoC-2009-Application-Aaron-Meurer).

  - type: textarea
    id: proposal_goals
    attributes:
      label: Goals
      description: What do you hope to achieve? This should be your project abstract and include a detailed description of the proposed work.
    validations:
      required: true

  - type: textarea
    id: proposal_why
    attributes:
      label: Why this project?
      description: What excites you about the proposed project and why?
    validations:
      required: true

  - type: textarea
    id: proposal_qualifications
    attributes:
      label: Qualifications
      description: What qualifications do you have to execute on your proposal? How are you suited to work on this project? For example, if you are interested in implementing statistical hypothesis tests, what courses have you taken or books have you read on statistics?
    validations:
      required: true

  - type: textarea
    id: proposal_commitment
    attributes:
      label: Commitment
      description: How much time do you plan to invest in the project before, during, and after the Google Summer of Code program? E.g., for part-time contributors, we expect ~15 hr/week during GSoC based on a 12 week schedule, but we request that you be explicit in your commitment. If you have other commitments, such as if you plan on taking any vacations or time away, have other jobs, or will be busy with exams during the program, let us know about it here.
    validations:
      required: true

  - type: textarea
    id: proposal_schedule
    attributes:
      label: Schedule
      description: Please provide a weekly schedule of how your time will be spent on the subtasks of the project throughout the GSoC program and the expected deliverables. While this is only preliminary and can be adjusted later, if need be, providing such a schedule will help us monitor your progress throughout the program. During your project, understand that you will issue weekly progress reports against the proposed schedule. If you aim to perform any prepwork prior to week 1 (e.g., during the community bonding period), be sure to include that in your answer below. The template below assumes a 12 week schedule. If you are doing an alternate schedule, you can adjust the template accordingly.
      value: |
        Assuming a 12 week schedule,

        - **Community Bonding Period**:

        - **Week 1**:

        - **Week 2**:

        - **Week 3**:

        - **Week 4**:

        - **Week 5**:

        - **Week 6**: (midterm)

        - **Week 7**:

        - **Week 8**:

        - **Week 9**:

        - **Week 10**:

        - **Week 11**:

        - **Week 12**:

        - **Final Week**:

        Notes:

        - The community bonding period is a 3 week period built into GSoC to help you get to know the project community and participate in project discussion. This is an opportunity for you to setup your local development environment, learn how the project's source control works, refine your project plan, read any necessary documentation, and otherwise prepare to execute on your project project proposal.
        - Usually, even week 1 deliverables include some code.
        - By week 6, you need enough done at this point for your mentor to evaluate your progress and pass you. Usually, you want to be a bit more than halfway done.
        - By week 11, you may want to "code freeze" and focus on completing any tests and/or documentation.
        - During the final week, you'll be submitting your project.
    validations:
      required: true
